### ISSUE TITLE
Portrait screen resolution

### ISSUE THREAD

**Issue by Anthonipples** [fabsenet/adrilight#70] opened 2018-12-04 14:19 UTC
I was wondering if you have managed to get this to work on a portrait screen? the preview shows most of the spots off screen resulting in bottom half of LED strip being off.

**Comment by fabsenet** [comment] 2018-12-04 15:03
The currently released version has a shifted preview but it does not affect
actual color reading. Can you provide a screen shot? I do not see why a
rotated screen should be an issue.

**Comment by fabsenet** [comment] 2019-01-21 15:48
feel free to reply and/or reopen later. I close this issue for now because I cannot reproduce the issue and you are not responding.

**Closed by fabsenet** 2019-01-21 15:48 UTC
Labels: question, reproduction failed
