### ISSUE TITLE
Border distance problem in v2.0.7

### ISSUE THREAD

**Issue by psbeau** [fabsenet/adrilight#68] opened 2018-11-06 22:03 UTC
The border distance position is incorrect but the Preview Results show the true position when output to the LEDs. My monitor is 3840 x 2160 my video card is a Nvidia 1050Ti.
![adrilight](https://user-images.githubusercontent.com/6306547/48096677-bb538580-e20f-11e8-9bb7-7e625c106089.jpg)

**Comment by fabsenet** [comment] 2018-11-07 10:18
just to be sure, i understand you correctly:

- you selected a border distance of 1 yourself and want it like that
- the preview is then wrong, showing a much larger border distance
- but the preview and the actual colors of your leds show the same thing use the same screen position again yielding the same color?

**Comment by psbeau** [comment] 2018-11-07 17:14
Hi, yes to all three points.

Thanks

**Comment by ElDiablo830** [comment] 2018-11-07 20:00
Hello same here, since the update unfortunately.
The led stripes is showing colors from too far of the screen border. i guess it shows the centered black dot rectangles.

I have a 4k screen too with 3840*2160 and RTX2080.
It worked wonderfully last days and when i opened adrilight today it was not working, i checked settings, i had spot width  custom on 1 (as usual), sending not working but random colors works. when i changed spot width to 10 or more (below 10 stripe is off in ambilight sending mod) it works but get the color far from the border.

hope you can help with that, Awesom Fabsenet

<img width="690" alt="capture d ecran 23" src="https://user-images.githubusercontent.com/44848987/48157512-16e54800-e2d0-11e8-9ae7-3dffd40bba7f.png">

**Comment by psbeau** [comment] 2018-11-07 21:36
Border distance doesn't seem to have an effect until it is increased to:
280 x-direction
224 y-direction

On my system anyway

**Comment by ElDiablo830** [comment] 2018-11-07 21:42
Anyway i give you all my steps if can help. The first problem was the stripe off. So the only way for me to make it send again was slide border to 10. Then the trouble is same as the main post here. Quite strange indeed.

Good luck and thanks for support

**Comment by fabsenet** [comment] 2018-11-12 15:55
this is all so messed up. this part of adrilight is untouched by me since it was once upon a time written when it was still called *bambilight*. 

Can you guys live a little longer with the way it currently behaves to give me time to fix this from ground up, also fixing the spot count issues everyone experiencing?

**Comment by psbeau** [comment] 2018-11-12 17:04
No problem, thanks for all your hard work.

**Comment by Kaitoukid93** [comment] 2018-11-16 14:55
this part is the same with 2.0.6 on the code but some how when preview. the spot frame was shifted.I re-touch it on the preview.xaml so it went back to normal, I think it's just about the preview resolution

**Comment by fabsenet** [comment] 2018-11-16 15:21
@Kaitoukid93 i am not sure I really understand the exact position, where you changed the canvas left/top? you might be right but as I introduced the scaled down texture feature in the last release, it may be possible, i missed something in the preview unscaled! 

As I understand all others in this issue, it affects actual display of led colors as well.

Anyway, I decided to clean this all up. I started with a long overdue change to actually let the user input his/her led strip length and dont need to think about a virtual matrix. because every new user seems to fall in this trap. the way I already implemented it, it will reduce the existing values by lowering the Y value by two. most existing users will not notice this if everything works

**Comment by Kaitoukid93** [comment] 2018-11-16 15:39
@fabsenet  it's the preview spot, at first I saw my LED light up weird. It changed as the screen but a little bit wrong about the color, so I looked at the preview tab and see the frame is not in the center so I open the project code and compare to 2.0.6 version, they're all the same, so I change the value as I show you, step by step until I saw them at the right place, it took time but it's ok now,
![image](https://user-images.githubusercontent.com/40384831/48630828-c6689b80-e9ef-11e8-9a6e-78a1657f4f28.png)
 I think it will be nice if we can move the spot, and support multiple screens, so we can move the spot around screens as prismatik does.
Anyway, the way we put the number of the leds has its own advantage, simpler for beginner (just count the LED, of course sometime it can be hard if we mess up with the led number on the arduino code

**Comment by fabsenet** [comment] 2018-11-26 16:16
@psbeau , @ElDiablo830 , @..all 😄 : I am working on the spots and made huge progress today. I still have to test offset and mirror but it looks good so far.

@Kaitoukid93 I was thinking very long about your fixed canvas values as it should (and actually DOES!) depend on the screen size. The root cause for the shifted preview spots is actually the useless `Margin=4` in  https://github.com/fabsenet/adrilight/blob/fa6311cc8dda591b05d53716e729d9144e7b8280/adrilight/View/SettingsWindowComponents/Preview.xaml#L68

It was not noticeable in earlier versions because of the much larger Canvas because the image was not scaled down in earlier versions. The viewbox finally scales the preview up or down to make it fit. The next version will show the preview spots pixel perfect.

**Comment by psbeau** [comment] 2018-11-26 18:33
Great news.
I tried playing around with  Margin="..." and
Width="{Binding ScreenWidth}" Height="{Binding ScreenHeight}"
but it just moved and scaled the screen image, and had no effect on the output from the spots. I'll wait for the expert.
Thanks

**Comment by psbeau** [comment] 2019-01-19 14:08
So, I tried again with Adrilight-dev and it works!
I think, while playing around with 2.07, I must have corrupted something and that is why I got 14 errors. I I downloaded the zip and built it directly in Visual Studio and now it works fine, I see no problems with the output or the preview. It's taking 73MB of memory and about 5% CPU when watching constantly changing video. 'Sending' in the notification area is working.
Few things I have noted:
While building 2.08, there were 15 warnings, I cam copy and paste them if you want.
The link to the 'What's new' web page could not be found. 
It is very slow to start.
Overall, it's working great - thanks for your efforts I really like this project.
I'll continue using 2.08 and let you know of any issues.

One other thing - keyboard shortcut??
Cheers

**Comment by ElDiablo830** [comment] 2019-01-19 14:19
Hello, thanks for the support, i hope to see this release online soon
Congrats

Le sam. 19 janv. 2019 à 15:08, AbsenteeAtom <notifications@github.com> a
écrit :

**Comment by yapetus** [comment] 2019-04-10 12:58
Maybe someday you make also application for Android? Thank you! :)

**Comment by n00bhax** [comment] 2019-04-23 19:22
> While building 2.08

> I'll continue using 2.08 and let you know of any issues.

How do I get 2.08 and does it fix this issue?

**Comment by psbeau** [comment] 2019-04-23 20:44
> How do I get 2.08 and does it fix this issue?

Yes, it fixes the issue. You can download and build 2.08 in code/branches/dev.

**Comment by n00bhax** [comment] 2019-04-24 09:17
> build 2.08 in code

I've never build something from github and it looks difficult. Why isn't 2.08 in the release page as a .exe?

**Comment by fabsenet** [comment] 2019-04-24 09:50
the fix is in the dev branch, this is correct, but I usually test things somewhat extensively on my own hardware as each release is kind of risky on its own and quite a bit of work.

Also this border distance issue is only a minor thing as it only affects the preview. I suggest you just wait for next official release. Building the source on your own is possible but I would not suggest it just for having this fix faster. Especially if you have little experience.

**Comment by n00bhax** [comment] 2019-04-24 10:16
I always thought it wasn't only the preview because since the update 2.07 the top and bottom LED's have not been taking colours from the edge of the screen. (see gif)

![ezgif-5-7db9d9c6283d](https://user-images.githubusercontent.com/28760191/56652051-ae760180-668a-11e9-8ed4-98cda89d31d1.gif)

**Comment by fabsenet** [comment] 2019-04-24 12:10
I will check this.

**Comment by psbeau** [comment] 2019-04-24 12:43
> I will check this.
 "Also this border distance issue is only a minor thing as it only affects the preview"
I'm surprised to hear you say this Fabian, as we established, it affects the output to the LEDs.

**Closed** 2019-06-05 14:25 UTC
Labels: bug
